-- MySQL Script generated by MySQL Workbench
-- Wed Oct 22 12:06:20 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema OREGONASKDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OREGONASKDB` ;

-- -----------------------------------------------------
-- Schema OREGONASKDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OREGONASKDB` DEFAULT CHARACTER SET utf8 ;
USE `OREGONASKDB` ;

-- -----------------------------------------------------
-- Table `OREGONASKDB`.`program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OREGONASKDB`.`program` ;

CREATE TABLE IF NOT EXISTS `OREGONASKDB`.`program` (
  `program_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `license_number` VARCHAR(45) NULL DEFAULT NULL,
  `notes` VARCHAR(1000) NULL DEFAULT NULL,
  `contact_name` VARCHAR(1000) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `county` VARCHAR(45) NULL DEFAULT NULL,
  `school_served` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`program_id`),
  UNIQUE INDEX `program_un_id` (`name` ASC, `city` ASC, `school_served` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 36301
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `OREGONASKDB`.`program_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OREGONASKDB`.`program_info` ;

CREATE TABLE IF NOT EXISTS `OREGONASKDB`.`program_info` (
  `program_info_id` INT(11) NOT NULL AUTO_INCREMENT,
  `average_daily_attendance` VARCHAR(45) NULL DEFAULT NULL,
  `max_capacity` VARCHAR(45) NULL DEFAULT NULL,
  `offered_before_school` TINYINT(1) NULL DEFAULT NULL,
  `offered_after_school` TINYINT(1) NULL DEFAULT NULL,
  `offered_monday` TINYINT(1) NULL DEFAULT NULL,
  `offered_tuesday` TINYINT(1) NULL DEFAULT NULL,
  `offered_wednesday` TINYINT(1) NULL DEFAULT NULL,
  `offered_thursday` TINYINT(1) NULL DEFAULT NULL,
  `offered_friday` TINYINT(1) NULL DEFAULT NULL,
  `offered_saturday` TINYINT(1) NULL DEFAULT NULL,
  `offered_sunday` TINYINT(1) NULL DEFAULT NULL,
  `offered_weekends` TINYINT(1) NULL DEFAULT NULL,
  `offered_evenings` TINYINT(1) NULL DEFAULT NULL,
  `offered_breaks` TINYINT(1) NULL DEFAULT NULL,
  `average_hours_per_week` VARCHAR(45) NULL DEFAULT NULL,
  `food_provided_before_school` TINYINT(1) NULL DEFAULT NULL,
  `food_provided_after_school` TINYINT(1) NULL DEFAULT NULL,
  `food_provided_during_breaks` TINYINT(1) NULL DEFAULT NULL,
  `stem_offered` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`program_info_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13236
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `OREGONASKDB`.`program_info_by_year`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OREGONASKDB`.`program_info_by_year` ;

CREATE TABLE IF NOT EXISTS `OREGONASKDB`.`program_info_by_year` (
  `program_info_by_year_id` INT(11) NOT NULL AUTO_INCREMENT,
  `year` INT(11) NOT NULL,
  `program_id` INT(11) NOT NULL,
  `program_info_id` INT(11) NOT NULL,
  PRIMARY KEY (`program_info_by_year_id`),
  UNIQUE INDEX `program_info_un_id` (`year` ASC, `program_id` ASC),
  INDEX `fk_program_info_by_year_program_info1_idx` (`program_info_id` ASC),
  INDEX `fk_program_info_by_year_program1_idx` (`program_id` ASC),
  CONSTRAINT `fk_program_info_by_year_program1`
    FOREIGN KEY (`program_id`)
    REFERENCES `OREGONASKDB`.`program` (`program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_info_by_year_program_info1`
    FOREIGN KEY (`program_info_id`)
    REFERENCES `OREGONASKDB`.`program_info` (`program_info_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10037
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `OREGONASKDB`.`provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OREGONASKDB`.`provider` ;

CREATE TABLE IF NOT EXISTS `OREGONASKDB`.`provider` (
  `provider_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`provider_id`),
  UNIQUE INDEX `provider_id_UNIQUE` (`provider_id` ASC),
  UNIQUE INDEX `provider_un_in` (`name` ASC, `city` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9921
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `OREGONASKDB`.`school`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OREGONASKDB`.`school` ;

CREATE TABLE IF NOT EXISTS `OREGONASKDB`.`school` (
  `school_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `elementary` TINYINT(1) NULL DEFAULT '0',
  `middle` TINYINT(1) NULL DEFAULT '0',
  `high` TINYINT(1) NULL DEFAULT '0',
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `congressional_district` VARCHAR(45) NULL DEFAULT NULL,
  `county` VARCHAR(45) NULL DEFAULT NULL,
  `school_district` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`school_id`),
  UNIQUE INDEX `school_id_UNIQUE` (`school_id` ASC),
  UNIQUE INDEX `school_un_in` (`name` ASC, `city` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 24036
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `OREGONASKDB`.`program_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OREGONASKDB`.`program_link` ;

CREATE TABLE IF NOT EXISTS `OREGONASKDB`.`program_link` (
  `program_link_id` INT(11) NOT NULL AUTO_INCREMENT,
  `school_id` INT(11) NULL DEFAULT NULL,
  `provider_id` INT(11) NULL DEFAULT NULL,
  `program_id` INT(11) NOT NULL,
  PRIMARY KEY (`program_link_id`),
  UNIQUE INDEX `program_id_UNIQUE` (`program_id` ASC),
  INDEX `school_id_fk_idx` (`school_id` ASC),
  INDEX `provider_id_fk_idx` (`provider_id` ASC),
  INDEX `program_id_fk_idx` (`program_id` ASC),
  CONSTRAINT `fk_program_id`
    FOREIGN KEY (`program_id`)
    REFERENCES `OREGONASKDB`.`program` (`program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provider_id`
    FOREIGN KEY (`provider_id`)
    REFERENCES `OREGONASKDB`.`provider` (`provider_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `OREGONASKDB`.`school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 37645
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `OREGONASKDB`.`school_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OREGONASKDB`.`school_info` ;

CREATE TABLE IF NOT EXISTS `OREGONASKDB`.`school_info` (
  `school_info_id` INT(11) NOT NULL AUTO_INCREMENT,
  `total_student_count` VARCHAR(45) NULL DEFAULT NULL,
  `free_lunch_count` VARCHAR(45) NULL DEFAULT NULL,
  `reduced_lunch_count` VARCHAR(45) NULL DEFAULT NULL,
  `percent_meet_reading` VARCHAR(45) NULL DEFAULT NULL,
  `percent_minority` VARCHAR(45) NULL DEFAULT NULL,
  `percent_white` VARCHAR(45) NULL DEFAULT NULL,
  `percent_fr` VARCHAR(45) NULL DEFAULT NULL,
  `lo_grade_offered` VARCHAR(45) NULL DEFAULT NULL,
  `hi_grade_offered` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`school_info_id`),
  UNIQUE INDEX `school_info_id_UNIQUE` (`school_info_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11751
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `OREGONASKDB`.`school_info_by_year`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OREGONASKDB`.`school_info_by_year` ;

CREATE TABLE IF NOT EXISTS `OREGONASKDB`.`school_info_by_year` (
  `school_info_by_year_id` INT(11) NOT NULL AUTO_INCREMENT,
  `year` INT(11) NOT NULL,
  `school_id` INT(11) NOT NULL,
  `school_info_id` INT(11) NOT NULL,
  PRIMARY KEY (`school_info_by_year_id`),
  UNIQUE INDEX `school_info_by_year_id_UNIQUE` (`school_info_by_year_id` ASC),
  UNIQUE INDEX `school_info_un_id` (`year` ASC, `school_id` ASC),
  INDEX `fk_school_info_by_year_school1_idx` (`school_id` ASC),
  INDEX `fk_school_info_by_year_school_info1_idx` (`school_info_id` ASC),
  CONSTRAINT `fk_school_info_by_year_school1`
    FOREIGN KEY (`school_id`)
    REFERENCES `OREGONASKDB`.`school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_school_info_by_year_school_info1`
    FOREIGN KEY (`school_info_id`)
    REFERENCES `OREGONASKDB`.`school_info` (`school_info_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11673
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
