package org.oregonask.entities;

// Generated Jan 2, 2015 10:07:55 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.Hibernate;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * EmailAlternate generated by hbm2java
 */
@Entity
@Table(name = "EMAIL_ALTERNATE", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "EMAILALT", "CONTACT_FK" }),
		@UniqueConstraint(columnNames = "EMAILALT") })
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="id")
public class EmailAlternate implements java.io.Serializable,IEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String emailAlt;
	private Contact contact;

	public EmailAlternate() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "EMAILALT", unique = true, nullable = false, length = 100)
	@JsonProperty("EMAILALT")
	public String getEmailAlt() {
		return this.emailAlt;
	}

	public void setEmailAlt(String emailAlt) {
		this.emailAlt = emailAlt;
	}

	@ManyToOne
	@JoinColumn(name = "CONTACT_FK", nullable=false, insertable=false, updatable=false)
	@JsonProperty("CONTACT")
	public Contact getContact() {
		return this.contact;
	}
	
	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@Override
	public void initialize() {
		Hibernate.initialize(this.getContact());
	}

}
