package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NutritionLink generated by hbm2java
 */
@Entity
@Table(name = "NUTRITION_LINK", catalog = "OREGONASKDB", uniqueConstraints = @UniqueConstraint(columnNames = "NUTRITION_ID"))
public class NutritionLink implements java.io.Serializable {

	private Integer nutritionLinkId;
	private Integer schoolId;
	private Integer sponsorId;
	private int nutritionId;

	public NutritionLink() {
	}

	public NutritionLink(int nutritionId) {
		this.nutritionId = nutritionId;
	}

	public NutritionLink(Integer schoolId, Integer sponsorId, int nutritionId) {
		this.schoolId = schoolId;
		this.sponsorId = sponsorId;
		this.nutritionId = nutritionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NUTRITION_LINK_ID", unique = true, nullable = false)
	public Integer getNutritionLinkId() {
		return this.nutritionLinkId;
	}

	public void setNutritionLinkId(Integer nutritionLinkId) {
		this.nutritionLinkId = nutritionLinkId;
	}

	@Column(name = "SCHOOL_ID")
	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "SPONSOR_ID")
	public Integer getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(Integer sponsorId) {
		this.sponsorId = sponsorId;
	}

	@Column(name = "NUTRITION_ID", unique = true, nullable = false)
	public int getNutritionId() {
		return this.nutritionId;
	}

	public void setNutritionId(int nutritionId) {
		this.nutritionId = nutritionId;
	}

}
