package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NutritionInfoByYear generated by hbm2java
 */
@Entity
@Table(name = "NUTRITION_INFO_BY_YEAR", catalog = "OREGONASKDB")
public class NutritionInfoByYear implements java.io.Serializable {

	private Integer nutritionInfoByYearId;
	private int year;
	private int nutritionId;
	private int nutritionInfoId;

	public NutritionInfoByYear() {
	}

	public NutritionInfoByYear(int year, int nutritionId, int nutritionInfoId) {
		this.year = year;
		this.nutritionId = nutritionId;
		this.nutritionInfoId = nutritionInfoId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NUTRITION_INFO_BY_YEAR_ID", unique = true, nullable = false)
	public Integer getNutritionInfoByYearId() {
		return this.nutritionInfoByYearId;
	}

	public void setNutritionInfoByYearId(Integer nutritionInfoByYearId) {
		this.nutritionInfoByYearId = nutritionInfoByYearId;
	}

	@Column(name = "YEAR", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "NUTRITION_ID", nullable = false)
	public int getNutritionId() {
		return this.nutritionId;
	}

	public void setNutritionId(int nutritionId) {
		this.nutritionId = nutritionId;
	}

	@Column(name = "NUTRITION_INFO_ID", nullable = false)
	public int getNutritionInfoId() {
		return this.nutritionInfoId;
	}

	public void setNutritionInfoId(int nutritionInfoId) {
		this.nutritionInfoId = nutritionInfoId;
	}

}
