package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;  
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;  
import javax.persistence.GenerationType;
import javax.persistence.Id;  
import javax.persistence.JoinColumn;  
import javax.persistence.JoinTable;  
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;  
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Nutrition generated by hbm2java
 */
@Entity
@Table(name = "NUTRITION", catalog = "OREGONASKDB", uniqueConstraints = @UniqueConstraint(columnNames = "CNP_WEB_SCHOOL_NUMBER"))
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="id")
public class Nutrition implements java.io.Serializable,IEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer nutritionId;
	private String siteName;
	private String cnpWebSchoolNumber;
	private String street;
	private String city;
	private String zip;
	private String state;
	private String county;
	
	public Nutrition() {
	}
	
	@OneToOne
    @JoinTable(
    		name="NUTRITION_LINK",
    		joinColumns=@JoinColumn(name="SCHOOL_ID"),  
    		inverseJoinColumns=@JoinColumn(name="NUTRITION_ID")) 
	private School school;
//	
//	@OneToOne(fetch = FetchType.LAZY, cascade = { CascadeType.ALL })  
//    @JoinTable(name="NUTRITION_LINK", catalog = "OREGONASKDB",  
//    joinColumns={@JoinColumn(name="SPONSOR_ID", nullable = false, updatable = false)},  
//    inverseJoinColumns={@JoinColumn(name="NUTRITION_ID", nullable = false, updatable = false)})
//	private Sponsor sponsor;
	
//	@OneToMany
//	@JoinTable(
//            name="NUTRITION_INFO_BY_YEAR",
//            joinColumns = @JoinColumn( name="NUTRITION_ID"),
//            inverseJoinColumns = @JoinColumn( name="NUTRITION_INFO_ID")
//    )
	private Set<NutritionInfo> nutrition;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "NUTRITION_ID", unique = true, nullable = false)
	@JsonProperty("id")
	public Integer getNutritionId() {
		return this.nutritionId;
	}

	public void setNutritionId(Integer nutritionId) {
		this.nutritionId = nutritionId;
	}

	@Column(name = "SITE_NAME", nullable = false, length = 250)
	@JsonProperty("site_name")
	public String getSiteName() {
		return this.siteName;
	}

	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	@Column(name = "CNP_WEB_SCHOOL_NUMBER", unique = true, nullable = false, length = 45)
	@JsonProperty("cnp_web_school_number")
	public String getCnpWebSchoolNumber() {
		return this.cnpWebSchoolNumber;
	}

	public void setCnpWebSchoolNumber(String cnpWebSchoolNumber) {
		this.cnpWebSchoolNumber = cnpWebSchoolNumber;
	}

	@Column(name = "STREET", length = 250)
	@JsonProperty("street")
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "CITY", length = 45)
	@JsonProperty("city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ZIP", length = 45)
	@JsonProperty("zip")
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "STATE", length = 45)
	@JsonProperty("state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTY", length = 45)
	@JsonProperty("county")
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}
	
	//** Get School & Sponsor
	
	@JsonProperty("school")
	public School getSchool() {
		return this.school;
	}
	
	public void setSchool(School school) {
		this.school = school;
	}
//	
//	@JsonProperty("sponsor")
//	public Sponsor getSponsor() {
//		return this.sponsor;
//	}
//
//	public void setSponsor(Sponsor sponsor) {
//		this.sponsor = sponsor;
//	}

//	@JsonProperty("nutrition")
//	public Set<NutritionInfo> getNutritionInfo() {
//		return nutrition;
//	}
//
//	public void setNutritionInfo(Set<NutritionInfo> nutritionInfo) {
//		this.nutrition = nutritionInfo;
//	}

	@Override
	public void deepCopy(Object obj) {
		setNutritionId(((Nutrition) obj).getNutritionId());
		setSiteName(((Nutrition) obj).getSiteName());
		setCnpWebSchoolNumber(((Nutrition) obj).getCnpWebSchoolNumber());
		setStreet(((Nutrition) obj).getStreet());
		setCity(((Nutrition) obj).getCity());
		setZip(((Nutrition) obj).getZip());
		setState(((Nutrition) obj).getState());
		setCounty(((Nutrition) obj).getCounty());
		setSchool(((Nutrition) obj).getSchool());
		//setSponsor(((Nutrition) obj).getSponsor());
		//setNutritionInfo(((Nutrition) obj).getNutritionInfo());
	}

}
