package org.oregonask.entities;
// Generated Nov 11, 2014 2:42:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Nutrition generated by hbm2java
 */
@Entity
@Table(name = "NUTRITION", catalog = "OREGONASKDB", uniqueConstraints = {
		@UniqueConstraint(columnNames = "CNP_WEB_SCHOOL_NUMBER"),
		@UniqueConstraint(columnNames = "SITE_NUMBER") })
public class Nutrition implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String siteName;
	private String siteNumber;
	private String cnpWebSchoolNumber;
	private String programType;
	private String street;
	private String city;
	private String zip;
	private String state;
	private String county;
	private Integer schoolId;
	private Integer sponsorId;

	public Nutrition() {
	}

	public Nutrition(String siteName) {
		this.siteName = siteName;
	}

	public Nutrition(String siteName, String siteNumber,
			String cnpWebSchoolNumber, String programType, String street,
			String city, String zip, String state, String county,
			Integer schoolId, Integer sponsorId) {
		this.siteName = siteName;
		this.siteNumber = siteNumber;
		this.cnpWebSchoolNumber = cnpWebSchoolNumber;
		this.programType = programType;
		this.street = street;
		this.city = city;
		this.zip = zip;
		this.state = state;
		this.county = county;
		this.schoolId = schoolId;
		this.sponsorId = sponsorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "SITE_NAME", nullable = false, length = 250)
	public String getSiteName() {
		return this.siteName;
	}

	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	@Column(name = "SITE_NUMBER", unique = true, length = 45)
	public String getSiteNumber() {
		return this.siteNumber;
	}

	public void setSiteNumber(String siteNumber) {
		this.siteNumber = siteNumber;
	}

	@Column(name = "CNP_WEB_SCHOOL_NUMBER", unique = true, length = 45)
	public String getCnpWebSchoolNumber() {
		return this.cnpWebSchoolNumber;
	}

	public void setCnpWebSchoolNumber(String cnpWebSchoolNumber) {
		this.cnpWebSchoolNumber = cnpWebSchoolNumber;
	}

	@Column(name = "PROGRAM_TYPE", length = 100)
	public String getProgramType() {
		return this.programType;
	}

	public void setProgramType(String programType) {
		this.programType = programType;
	}

	@Column(name = "STREET", length = 250)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "CITY", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ZIP", length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "STATE", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTY", length = 45)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "SCHOOL_ID")
	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "SPONSOR_ID")
	public Integer getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(Integer sponsorId) {
		this.sponsorId = sponsorId;
	}

}
