package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NutritionInfo generated by hbm2java
 */
@Entity
@Table(name = "NUTRITION_INFO", catalog = "OREGONASKDB")
public class NutritionInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer nutritionInfoId;
	private Boolean breakfastServed;
	private Boolean pmSnackServed;
	private Boolean supperServed;
	private Integer year;
	
	public NutritionInfo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NUTRITION_INFO_ID", unique = true, nullable = false)
	public Integer getNutritionInfoId() {
		return this.nutritionInfoId;
	}

	public void setNutritionInfoId(Integer nutritionInfoId) {
		this.nutritionInfoId = nutritionInfoId;
	}

	@Column(name = "BREAKFAST_SERVED")
	public Boolean getBreakfastServed() {
		return this.breakfastServed;
	}

	public void setBreakfastServed(Boolean breakfastServed) {
		this.breakfastServed = breakfastServed;
	}

	@Column(name = "PM_SNACK_SERVED")
	public Boolean getPmSnackServed() {
		return this.pmSnackServed;
	}

	public void setPmSnackServed(Boolean pmSnackServed) {
		this.pmSnackServed = pmSnackServed;
	}

	@Column(name = "SUPPER_SERVED")
	public Boolean getSupperServed() {
		return this.supperServed;
	}

	public void setSupperServed(Boolean supperServed) {
		this.supperServed = supperServed;
	}

	@Column(name = "YEAR", nullable = false)
	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}
}
