package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * NutritionInfo generated by hbm2java
 */
@Entity
@Table(name = "NUTRITION_INFO", catalog = "OREGONASKDB")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="id")
public class NutritionInfo implements java.io.Serializable,IEntity {

	private static final long serialVersionUID = 1L;
	
	private Integer nutritionInfoId;
	private Boolean breakfastServed;
	private Boolean pmSnackServed;
	private Boolean supperServed;
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = { CascadeType.ALL })
	@JoinTable(name="nutrition_info_by_year", catalog = "OREGONASKDB",  
    joinColumns={@JoinColumn(name="nutrition_id", nullable = false, updatable = false)},  
    inverseJoinColumns={@JoinColumn(name="nutrition_info_id", nullable = false, updatable = false)})
	private Set<Nutrition> nutrition;

	public NutritionInfo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NUTRITION_INFO_ID", unique = true, nullable = false)
	public Integer getNutritionInfoId() {
		return this.nutritionInfoId;
	}

	public void setNutritionInfoId(Integer nutritionInfoId) {
		this.nutritionInfoId = nutritionInfoId;
	}

	@Column(name = "BREAKFAST_SERVED")
	public Boolean getBreakfastServed() {
		return this.breakfastServed;
	}

	public void setBreakfastServed(Boolean breakfastServed) {
		this.breakfastServed = breakfastServed;
	}

	@Column(name = "PM_SNACK_SERVED")
	public Boolean getPmSnackServed() {
		return this.pmSnackServed;
	}

	public void setPmSnackServed(Boolean pmSnackServed) {
		this.pmSnackServed = pmSnackServed;
	}

	@Column(name = "SUPPER_SERVED")
	public Boolean getSupperServed() {
		return this.supperServed;
	}

	public void setSupperServed(Boolean supperServed) {
		this.supperServed = supperServed;
	}

	@Override
	public void deepCopy(Object obj) {
		setNutritionInfoId(((NutritionInfo) obj).getNutritionInfoId());
		setBreakfastServed(((NutritionInfo) obj).getBreakfastServed());
		setPmSnackServed(((NutritionInfo) obj).getPmSnackServed());
		setSupperServed(((NutritionInfo) obj).getSupperServed());
	}
}
