package org.oregonask.entities;
// Generated Nov 11, 2014 2:42:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name = "PROGRAM", catalog = "OREGONASKDB", uniqueConstraints = @UniqueConstraint(columnNames = {
		"NAME", "CITY", "SCHOOL_SERVED" }))
public class Program implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String licenseNumber;
	private String notes;
	private String contactName;
	private String email;
	private String phone;
	private String city;
	private String state;
	private String zip;
	private String street;
	private String county;
	private String schoolServed;
	private Integer sponsorId;
	private Integer schoolId;

	public Program() {
	}

	public Program(String name) {
		this.name = name;
	}

	public Program(String name, String licenseNumber, String notes,
			String contactName, String email, String phone, String city,
			String state, String zip, String street, String county,
			String schoolServed, Integer sponsorId, Integer schoolId) {
		this.name = name;
		this.licenseNumber = licenseNumber;
		this.notes = notes;
		this.contactName = contactName;
		this.email = email;
		this.phone = phone;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.street = street;
		this.county = county;
		this.schoolServed = schoolServed;
		this.sponsorId = sponsorId;
		this.schoolId = schoolId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LICENSE_NUMBER", length = 45)
	public String getLicenseNumber() {
		return this.licenseNumber;
	}

	public void setLicenseNumber(String licenseNumber) {
		this.licenseNumber = licenseNumber;
	}

	@Column(name = "NOTES", length = 1000)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "CONTACT_NAME", length = 1000)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "EMAIL", length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHONE", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "CITY", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP", length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "STREET", length = 45)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "COUNTY", length = 45)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "SCHOOL_SERVED", length = 250)
	public String getSchoolServed() {
		return this.schoolServed;
	}

	public void setSchoolServed(String schoolServed) {
		this.schoolServed = schoolServed;
	}

	@Column(name = "SPONSOR_ID")
	public Integer getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(Integer sponsorId) {
		this.sponsorId = sponsorId;
	}

	@Column(name = "SCHOOL_ID")
	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

}
