package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProgramInfoByYear generated by hbm2java
 */
@Entity
@Table(name = "PROGRAM_INFO_BY_YEAR", catalog = "OREGONASKDB", uniqueConstraints = @UniqueConstraint(columnNames = {
		"YEAR", "PROGRAM_ID" }))
public class ProgramInfoByYear implements java.io.Serializable {

	private Integer programInfoByYearId;
	private int year;
	private int programId;
	private int programInfoId;

	public ProgramInfoByYear() {
	}

	public ProgramInfoByYear(int year, int programId, int programInfoId) {
		this.year = year;
		this.programId = programId;
		this.programInfoId = programInfoId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PROGRAM_INFO_BY_YEAR_ID", unique = true, nullable = false)
	public Integer getProgramInfoByYearId() {
		return this.programInfoByYearId;
	}

	public void setProgramInfoByYearId(Integer programInfoByYearId) {
		this.programInfoByYearId = programInfoByYearId;
	}

	@Column(name = "YEAR", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "PROGRAM_ID", nullable = false)
	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

	@Column(name = "PROGRAM_INFO_ID", nullable = false)
	public int getProgramInfoId() {
		return this.programInfoId;
	}

	public void setProgramInfoId(int programInfoId) {
		this.programInfoId = programInfoId;
	}

}
