package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name = "PROGRAM", catalog = "OREGONASKDB", uniqueConstraints = @UniqueConstraint(columnNames = {
		"NAME", "CITY", "SCHOOL_SERVED" }))
public class Program implements java.io.Serializable,IEntity {

	private static final long serialVersionUID = 8618940262002043855L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PROGRAM_ID", unique = true, nullable = false)
	private Integer programId;
	
	@Column(name = "NAME", nullable = false, length = 250)
	private String name;
	
	@Column(name = "LICENSE_NUMBER", length = 45)
	private String licenseNumber;
	
	@Column(name = "NOTES", length = 1000)
	private String notes;
	
	@Column(name = "CONTACT_NAME", length = 1000)
	private String contactName;
	
	@Column(name = "EMAIL", length = 250)
	private String email;
	
	@Column(name = "PHONE", length = 45)
	private String phone;
	
	@Column(name = "CITY", length = 45)
	private String city;
	
	@Column(name = "STATE", length = 45)
	private String state;
	
	@Column(name = "ZIP", length = 45)
	private String zip;
	
	@Column(name = "STREET", length = 45)
	private String street;
	
	@Column(name = "COUNTY", length = 45)
	private String county;
	
	@Column(name = "SCHOOL_SERVED", length = 250)
	private String schoolServed;
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "programBySchool")
	private Set<School> school;
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "programBySponsor")
	private Set<Sponsor> sponsor;
	
	@OneToMany(fetch=FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinTable(name="PROGRAM_INFO_BY_YEAR", 
			joinColumns=@JoinColumn(name="PROGRAM_ID"),
			inverseJoinColumns=@JoinColumn(name="PROGRAM_INFO_ID"))
	private Set<ProgramInfo> programInfo;

	public Program() {
	}

	
	public Integer getProgramId() {
		return this.programId;
	}

	public void setProgramId(Integer programId) {
		this.programId = programId;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public String getLicenseNumber() {
		return this.licenseNumber;
	}

	public void setLicenseNumber(String licenseNumber) {
		this.licenseNumber = licenseNumber;
	}

	
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	
	public String getSchoolServed() {
		return this.schoolServed;
	}

	public void setSchoolServed(String schoolServed) {
		this.schoolServed = schoolServed;
	}

	public Set<School> getSchool() {
		return school;
	}


	public void setSchool(Set<School> school) {
		this.school = school;
	}


	public Set<Sponsor> getSponsor() {
		return sponsor;
	}


	public void setSponsor(Set<Sponsor> sponsor) {
		this.sponsor = sponsor;
	}


	public Set<ProgramInfo> getProgramInfo() {
		return programInfo;
	}


	public void setProgramInfo(Set<ProgramInfo> programInfo) {
		this.programInfo = programInfo;
	}


	@Override
	public void deepCopy(Object obj) {
		setCity(((Program) obj).getCity());
		setContactName(((Program) obj).getContactName());
		setCounty(((Program) obj).getCounty());
		setEmail(((Program) obj).getEmail());
		setLicenseNumber(((Program) obj).getLicenseNumber());
		setName(((Program) obj).getName());
		setNotes(((Program) obj).getNotes());
		setPhone(((Program) obj).getPhone());
		setProgramId(((Program) obj).getProgramId());
		setProgramInfo(((Program) obj).getProgramInfo());
		setSchool(((Program) obj).getSchool());
		setSchoolServed(((Program) obj).getSchoolServed());
		setSponsor(((Program) obj).getSponsor());
		setState(((Program) obj).getState());
		setStreet(((Program) obj).getStreet());
		setZip(((Program) obj).getZip());
	}

}
