package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * School generated by hbm2java
 */
@Entity
@Table(name = "SCHOOL", catalog = "OREGONASKDB", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "NAME", "COUNTY" }),
		@UniqueConstraint(columnNames = "INSTITUTION_ID") })

@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="id")
public class School implements java.io.Serializable,IEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5054829261229547595L;
	
	private Integer schoolId;
	private Integer institutionId;
	private String name;
	private Boolean elementary;
	private Boolean middle;
	private Boolean high;
	private String city;
	private String state;
	private String zip;
	private String street;
	private String congressionalDistrict;
	private String county;
	private String schoolDistrict;

	public School() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "SCHOOL_ID", unique = true, nullable = false)
	@JsonProperty("id")
	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "INSTITUTION_ID", unique = true)
	@JsonProperty("institution_id")
	public Integer getInstitutionId() {
		return this.institutionId;
	}

	public void setInstitutionId(Integer institutionId) {
		this.institutionId = institutionId;
	}

	@Column(name = "NAME", nullable = false, length = 250)
	@JsonProperty("name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ELEMENTARY")
	@JsonProperty("elementary")
	public Boolean getElementary() {
		return this.elementary;
	}

	public void setElementary(Boolean elementary) {
		this.elementary = elementary;
	}

	@Column(name = "MIDDLE")
	@JsonProperty("middle")
	public Boolean getMiddle() {
		return this.middle;
	}

	public void setMiddle(Boolean middle) {
		this.middle = middle;
	}

	@Column(name = "HIGH")
	@JsonProperty("high")
	public Boolean getHigh() {
		return this.high;
	}

	public void setHigh(Boolean high) {
		this.high = high;
	}

	@Column(name = "CITY", length = 45)
	@JsonProperty("city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 45)
	@JsonProperty("state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP", length = 45)
	@JsonProperty("zip")
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "STREET", length = 45)
	@JsonProperty("street")
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "CONGRESSIONAL_DISTRICT", length = 45)
	@JsonProperty("congressional_district")
	public String getCongressionalDistrict() {
		return this.congressionalDistrict;
	}

	public void setCongressionalDistrict(String congressionalDistrict) {
		this.congressionalDistrict = congressionalDistrict;
	}

	@Column(name = "COUNTY", length = 45)
	@JsonProperty("county")
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "SCHOOL_DISTRICT", length = 45)
	@JsonProperty("school_district")
	public String getSchoolDistrict() {
		return this.schoolDistrict;
	}

	public void setSchoolDistrict(String schoolDistrict) {
		this.schoolDistrict = schoolDistrict;
	}

	@Override
	public void deepCopy(Object obj) {
		setSchoolId(((School) obj).getSchoolId());
		setInstitutionId(((School) obj).getInstitutionId());
		setName(((School) obj).getName());
		setElementary(((School) obj).getElementary());
		setMiddle(((School) obj).getElementary());
		setHigh(((School) obj).getHigh());
		setCity(((School) obj).getCity());
		setState(((School) obj).getState());
		setZip(((School) obj).getZip());
		setStreet(((School) obj).getStreet());
		setCongressionalDistrict(((School) obj).getCongressionalDistrict());
		setCounty(((School) obj).getCounty());
		setSchoolDistrict(((School) obj).getSchoolDistrict());
	}

}
