package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SchoolInfoByYear generated by hbm2java
 */
@Entity
@Table(name = "SCHOOL_INFO_BY_YEAR", catalog = "OREGONASKDB", uniqueConstraints = @UniqueConstraint(columnNames = {
		"YEAR", "SCHOOL_ID" }))
public class SchoolInfoByYear implements java.io.Serializable {

	private Integer schoolInfoByYearId;
	private int year;
	private int schoolId;
	private int schoolInfoId;

	public SchoolInfoByYear() {
	}

	public SchoolInfoByYear(int year, int schoolId, int schoolInfoId) {
		this.year = year;
		this.schoolId = schoolId;
		this.schoolInfoId = schoolInfoId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SCHOOL_INFO_BY_YEAR_ID", unique = true, nullable = false)
	public Integer getSchoolInfoByYearId() {
		return this.schoolInfoByYearId;
	}

	public void setSchoolInfoByYearId(Integer schoolInfoByYearId) {
		this.schoolInfoByYearId = schoolInfoByYearId;
	}

	@Column(name = "YEAR", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "SCHOOL_ID", nullable = false)
	public int getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(int schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "SCHOOL_INFO_ID", nullable = false)
	public int getSchoolInfoId() {
		return this.schoolInfoId;
	}

	public void setSchoolInfoId(int schoolInfoId) {
		this.schoolInfoId = schoolInfoId;
	}

}
