package org.oregonask.entities;
// Generated Nov 11, 2014 2:42:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * School generated by hbm2java
 */
@Entity
@Table(name = "SCHOOL", catalog = "OREGONASKDB", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "NAME", "COUNTY" }),
		@UniqueConstraint(columnNames = "INSTITUTION_ID") })
public class School implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer institutionId;
	private String name;
	private Boolean elementary;
	private Boolean middle;
	private Boolean high;
	private String city;
	private String state;
	private String zip;
	private String street;
	private String congressionalDistrict;
	private String county;
	private String schoolDistrict;

	public School() {
	}

	public School(String name) {
		this.name = name;
	}

	public School(Integer institutionId, String name, Boolean elementary,
			Boolean middle, Boolean high, String city, String state,
			String zip, String street, String congressionalDistrict,
			String county, String schoolDistrict) {
		this.institutionId = institutionId;
		this.name = name;
		this.elementary = elementary;
		this.middle = middle;
		this.high = high;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.street = street;
		this.congressionalDistrict = congressionalDistrict;
		this.county = county;
		this.schoolDistrict = schoolDistrict;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "INSTITUTION_ID", unique = true)
	public Integer getInstitutionId() {
		return this.institutionId;
	}

	public void setInstitutionId(Integer institutionId) {
		this.institutionId = institutionId;
	}

	@Column(name = "NAME", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ELEMENTARY")
	public Boolean getElementary() {
		return this.elementary;
	}

	public void setElementary(Boolean elementary) {
		this.elementary = elementary;
	}

	@Column(name = "MIDDLE")
	public Boolean getMiddle() {
		return this.middle;
	}

	public void setMiddle(Boolean middle) {
		this.middle = middle;
	}

	@Column(name = "HIGH")
	public Boolean getHigh() {
		return this.high;
	}

	public void setHigh(Boolean high) {
		this.high = high;
	}

	@Column(name = "CITY", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP", length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "STREET", length = 45)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "CONGRESSIONAL_DISTRICT", length = 45)
	public String getCongressionalDistrict() {
		return this.congressionalDistrict;
	}

	public void setCongressionalDistrict(String congressionalDistrict) {
		this.congressionalDistrict = congressionalDistrict;
	}

	@Column(name = "COUNTY", length = 45)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "SCHOOL_DISTRICT", length = 45)
	public String getSchoolDistrict() {
		return this.schoolDistrict;
	}

	public void setSchoolDistrict(String schoolDistrict) {
		this.schoolDistrict = schoolDistrict;
	}

}
