package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SchoolInfo generated by hbm2java
 */
@Entity
@Table(name = "SCHOOL_INFO", catalog = "OREGONASKDB")
public class SchoolInfo implements java.io.Serializable {

	private static final long serialVersionUID = 5443992434125924778L;
	
	private Integer schoolInfoId;
	private String totalStudentCount;
	private String freeLunchCount;
	private String reducedLunchCount;
	private String percentMeetReading;
	private String percentMinority;
	private String percentWhite;
	private String percentFr;
	private String loGradeOffered;
	private String hiGradeOffered;
	
	@Column(name = "YEAR")
	private Integer year;

	public SchoolInfo() {
	}

	public SchoolInfo(String totalStudentCount, String freeLunchCount,
			String reducedLunchCount, String percentMeetReading,
			String percentMinority, String percentWhite, String percentFr,
			String loGradeOffered, String hiGradeOffered) {
		this.totalStudentCount = totalStudentCount;
		this.freeLunchCount = freeLunchCount;
		this.reducedLunchCount = reducedLunchCount;
		this.percentMeetReading = percentMeetReading;
		this.percentMinority = percentMinority;
		this.percentWhite = percentWhite;
		this.percentFr = percentFr;
		this.loGradeOffered = loGradeOffered;
		this.hiGradeOffered = hiGradeOffered;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SCHOOL_INFO_ID", unique = true, nullable = false)
	public Integer getSchoolInfoId() {
		return this.schoolInfoId;
	}

	public void setSchoolInfoId(Integer schoolInfoId) {
		this.schoolInfoId = schoolInfoId;
	}

	@Column(name = "TOTAL_STUDENT_COUNT", length = 45)
	public String getTotalStudentCount() {
		return this.totalStudentCount;
	}

	public void setTotalStudentCount(String totalStudentCount) {
		this.totalStudentCount = totalStudentCount;
	}

	@Column(name = "FREE_LUNCH_COUNT", length = 45)
	public String getFreeLunchCount() {
		return this.freeLunchCount;
	}

	public void setFreeLunchCount(String freeLunchCount) {
		this.freeLunchCount = freeLunchCount;
	}

	@Column(name = "REDUCED_LUNCH_COUNT", length = 45)
	public String getReducedLunchCount() {
		return this.reducedLunchCount;
	}

	public void setReducedLunchCount(String reducedLunchCount) {
		this.reducedLunchCount = reducedLunchCount;
	}

	@Column(name = "PERCENT_MEET_READING", length = 45)
	public String getPercentMeetReading() {
		return this.percentMeetReading;
	}

	public void setPercentMeetReading(String percentMeetReading) {
		this.percentMeetReading = percentMeetReading;
	}

	@Column(name = "PERCENT_MINORITY", length = 45)
	public String getPercentMinority() {
		return this.percentMinority;
	}

	public void setPercentMinority(String percentMinority) {
		this.percentMinority = percentMinority;
	}

	@Column(name = "PERCENT_WHITE", length = 45)
	public String getPercentWhite() {
		return this.percentWhite;
	}

	public void setPercentWhite(String percentWhite) {
		this.percentWhite = percentWhite;
	}

	@Column(name = "PERCENT_FR", length = 45)
	public String getPercentFr() {
		return this.percentFr;
	}

	public void setPercentFr(String percentFr) {
		this.percentFr = percentFr;
	}

	@Column(name = "LO_GRADE_OFFERED", length = 45)
	public String getLoGradeOffered() {
		return this.loGradeOffered;
	}

	public void setLoGradeOffered(String loGradeOffered) {
		this.loGradeOffered = loGradeOffered;
	}

	@Column(name = "HI_GRADE_OFFERED", length = 45)
	public String getHiGradeOffered() {
		return this.hiGradeOffered;
	}

	public void setHiGradeOffered(String hiGradeOffered) {
		this.hiGradeOffered = hiGradeOffered;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

}
