package org.oregonask.entities;
// Generated Nov 11, 2014 2:42:57 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.Hibernate;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * School generated by hbm2java
 */
@Entity
@Table(name = "SCHOOL", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "NAME", "COUNTY" }),
		@UniqueConstraint(columnNames = "INSTITUTION_ID") })
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="id")
public class School implements java.io.Serializable, IEntity,IUpdateLastEditBy {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1129066540963317543L;
	private Integer id;
	private Integer institutionId;
	private String name;
	private Boolean elementary;
	private Boolean middle;
	private Boolean high;
	private String city;
	private String state;
	private String zip;
	private String street;
	private String congressionalDistrict;
	private String county;
	private String schoolDistrict;
	private String timeStamp;
	private String lastEditBy;
	private Set<SchoolInfo> SchoolInfo;
	private Set<Summerfood> SummerFood;
	private Set<Nutrition> Nutrition;
	private Set<Program> Program;

	public School() {}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "INSTITUTION_ID", unique = true)
	@JsonProperty("INSTITUTION_ID")
	public Integer getInstitutionId() {
		return this.institutionId;
	}

	public void setInstitutionId(Integer institutionId) {
		this.institutionId = institutionId;
	}

	@Column(name = "NAME", nullable = false, length = 250)
	@JsonProperty("NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ELEMENTARY")
	@JsonProperty("ELEMENTARY")
	public Boolean getElementary() {
		return this.elementary;
	}

	public void setElementary(Boolean elementary) {
		this.elementary = elementary;
	}

	@Column(name = "MIDDLE")
	@JsonProperty("MIDDLE")
	public Boolean getMiddle() {
		return this.middle;
	}

	public void setMiddle(Boolean middle) {
		this.middle = middle;
	}

	@Column(name = "HIGH")
	@JsonProperty("HIGH")
	public Boolean getHigh() {
		return this.high;
	}

	public void setHigh(Boolean high) {
		this.high = high;
	}

	@Column(name = "CITY", length = 45)
	@JsonProperty("CITY")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 45)
	@JsonProperty("STATE")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP", length = 45)
	@JsonProperty("ZIP")
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "STREET", length = 45)
	@JsonProperty("STREET")
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "CONGRESSIONAL_DISTRICT", length = 45)
	@JsonProperty("CONGRESSIONAL_DISTRICT")
	public String getCongressionalDistrict() {
		return this.congressionalDistrict;
	}

	public void setCongressionalDistrict(String congressionalDistrict) {
		this.congressionalDistrict = congressionalDistrict;
	}

	@Column(name = "COUNTY", length = 45)
	@JsonProperty("COUNTY")
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "SCHOOL_DISTRICT", length = 45)
	@JsonProperty("SCHOOL_DISTRICT")
	public String getSchoolDistrict() {
		return this.schoolDistrict;
	}

	public void setSchoolDistrict(String schoolDistrict) {
		this.schoolDistrict = schoolDistrict;
	}

	@Column(name = "TIME_STAMP")
	@JsonProperty("TIME_STAMP")
	public String getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(String timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "LAST_EDIT_BY", length = 100)
	@JsonProperty("LAST_EDIT_BY")
	public String getLastEditBy() {
		return lastEditBy;
	}

	public void setLastEditBy(String lastEditBy) {
		this.lastEditBy = lastEditBy;
	}

	@OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL})
	@JoinColumn(name="school_id")
	@JsonProperty("SCHOOL_INFO")
	public Set<SchoolInfo> getSchoolInfo() {
		return SchoolInfo;
	}

	public void setSchoolInfo(Set<SchoolInfo> schoolInfo) {
		SchoolInfo = schoolInfo;
	}

	@OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL})
	@JoinColumn(name="school_id")
	public Set<Summerfood> getSummerfoods() {
		return SummerFood;
	}

	public void setSummerfoods(Set<Summerfood> summerfoods) {
		this.SummerFood = summerfoods;
	}

	@OneToMany(mappedBy="school", fetch=FetchType.LAZY)
	@JsonProperty("NUTRITION")
	public Set<Nutrition> getNutritions() {
		return Nutrition;
	}

	public void setNutritions(Set<Nutrition> nutritions) {
		this.Nutrition = nutritions;
	}

	@OneToMany(mappedBy="school", fetch=FetchType.LAZY)
	@JsonProperty("PROGRAM")
	public Set<Program> getPrograms() {
		return Program;
	}

	public void setPrograms(Set<Program> programs) {
		this.Program = programs;
	}

	@Override
	public void initialize() {
		Hibernate.initialize(this.getSchoolInfo());
		Hibernate.initialize(this.getSummerfoods());
		Hibernate.initialize(this.getNutritions());
		Hibernate.initialize(this.getPrograms());
	}
}
