package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Sponsor generated by hbm2java
 */
@Entity
@Table(name = "SPONSOR", catalog = "OREGONASKDB", uniqueConstraints = {
		@UniqueConstraint(columnNames = "NAME"),
		@UniqueConstraint(columnNames = "AGR_NUMBER") })
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="id")
public class Sponsor implements java.io.Serializable,IEntity {

	private static final long serialVersionUID = -4263127826708928763L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SPONSOR_ID", unique = true, nullable = false)
	private Integer sponsorId;
	
	@Column(name = "NAME", unique = true, nullable = false, length = 250)
	private String name;
	
	@Column(name = "AGR_NUMBER", unique = true, length = 45)
	private String agrNumber;
	
	@Column(name = "SPONSOR_TYPE", length = 45)
	private String sponsorType;
	
	@OneToMany(fetch=FetchType.LAZY, cascade=CascadeType.ALL)  
	@JoinTable(name="NUTRITION_LINK",  
		joinColumns=@JoinColumn(name="SPONSOR_ID"),  
		inverseJoinColumns=@JoinColumn(name="NUTRITION_ID")) 
	Set<Nutrition> nutritionBySponsor;
	
	@OneToMany(fetch=FetchType.LAZY, cascade=CascadeType.ALL)  
	@JoinTable(name="SUMMERFOOD_LINK",  
		joinColumns=@JoinColumn(name="SPONSOR_ID"),  
		inverseJoinColumns=@JoinColumn(name="SUMMERFOOD_ID")) 
	Set<Summerfood> summerfoodBySponsor;
	
	@OneToMany(fetch=FetchType.LAZY, cascade=CascadeType.ALL)  
	@JoinTable(name="YMCACW_LINK",  
		joinColumns=@JoinColumn(name="SPONSOR_ID"),  
		inverseJoinColumns=@JoinColumn(name="program_ID")) 
	Set<Summerfood> programBySponsor;

	public Sponsor() {
	}

	@JsonProperty("id")
	public Integer getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(Integer sponsorId) {
		this.sponsorId = sponsorId;
	}

	@JsonProperty("name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@JsonProperty("agr_number")
	public String getAgrNumber() {
		return this.agrNumber;
	}

	public void setAgrNumber(String agrNumber) {
		this.agrNumber = agrNumber;
	}

	@JsonProperty("sponsor_type")
	public String getSponsorType() {
		return this.sponsorType;
	}

	public void setSponsorType(String sponsorType) {
		this.sponsorType = sponsorType;
	}
	
	@JsonProperty("nutrition")
	public Set<Nutrition> getNutritionBySponsor() {
		return nutritionBySponsor;
	}

	public void setNutritionBySponsor(Set<Nutrition> nutritionBySponsor) {
		this.nutritionBySponsor = nutritionBySponsor;
	}

	@JsonProperty("summerfood")
	public Set<Summerfood> getSummerfoodBySponsor() {
		return summerfoodBySponsor;
	}

	public void setSummerfoodBySponsor(Set<Summerfood> summerfoodBySponsor) {
		this.summerfoodBySponsor = summerfoodBySponsor;
	}

	@JsonProperty("program")
	public Set<Summerfood> getProgramBySponsor() {
		return programBySponsor;
	}

	public void setProgramBySponsor(Set<Summerfood> programBySponsor) {
		this.programBySponsor = programBySponsor;
	}

	@Override
	public void deepCopy(Object obj) {
		setSponsorId(((Sponsor) obj).getSponsorId());
		setName(((Sponsor) obj).getName());
		setAgrNumber(((Sponsor) obj).getAgrNumber());
		setSponsorType(((Sponsor) obj).getSponsorType());
		setNutritionBySponsor(((Sponsor) obj).getNutritionBySponsor());
		setSummerfoodBySponsor(((Sponsor) obj).getSummerfoodBySponsor());
		setProgramBySponsor(((Sponsor) obj).getProgramBySponsor());
	}

}
