package org.oregonask.entities;
// Generated Nov 11, 2014 2:42:57 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sponsor generated by hbm2java
 */
@Entity
@Table(name = "SPONSOR", catalog = "OREGONASKDB", uniqueConstraints = {
		@UniqueConstraint(columnNames = "NAME"),
		@UniqueConstraint(columnNames = "AGR_NUMBER") })
public class Sponsor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String agrNumber;
	private String sponsorType;

	public Sponsor() {
	}

	public Sponsor(String name) {
		this.name = name;
	}

	public Sponsor(String name, String agrNumber, String sponsorType) {
		this.name = name;
		this.agrNumber = agrNumber;
		this.sponsorType = sponsorType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "AGR_NUMBER", unique = true, length = 45)
	public String getAgrNumber() {
		return this.agrNumber;
	}

	public void setAgrNumber(String agrNumber) {
		this.agrNumber = agrNumber;
	}

	@Column(name = "SPONSOR_TYPE", length = 45)
	public String getSponsorType() {
		return this.sponsorType;
	}

	public void setSponsorType(String sponsorType) {
		this.sponsorType = sponsorType;
	}

}
