package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Sponsor generated by hbm2java
 */
@Entity
@Table(name = "SPONSOR", catalog = "OREGONASKDB", uniqueConstraints = {
		@UniqueConstraint(columnNames = "NAME"),
		@UniqueConstraint(columnNames = "AGR_NUMBER") })
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="id")
public class Sponsor implements java.io.Serializable,IEntity {

	private static final long serialVersionUID = 1L;
	
	private Integer sponsorId;
	private String name;
	private String agrNumber;
	private String sponsorType;

	public Sponsor() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SPONSOR_ID", unique = true, nullable = false)
	public Integer getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(Integer sponsorId) {
		this.sponsorId = sponsorId;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "AGR_NUMBER", unique = true, length = 45)
	public String getAgrNumber() {
		return this.agrNumber;
	}

	public void setAgrNumber(String agrNumber) {
		this.agrNumber = agrNumber;
	}

	@Column(name = "SPONSOR_TYPE", length = 45)
	public String getSponsorType() {
		return this.sponsorType;
	}

	public void setSponsorType(String sponsorType) {
		this.sponsorType = sponsorType;
	}
	
	@Override
	public void deepCopy(Object obj) {
		setSponsorId(((Sponsor) obj).getSponsorId());
		setName(((Sponsor) obj).getName());
		setAgrNumber(((Sponsor) obj).getAgrNumber());
		setSponsorType(((Sponsor) obj).getSponsorType());
	}

}
