package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Summerfood generated by hbm2java
 */
@Entity
@Table(name = "SUMMERFOOD", catalog = "OREGONASKDB", uniqueConstraints = @UniqueConstraint(columnNames = "SITE_NUMBER"))
public class Summerfood implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer summerfoodId;
	private String siteName;
	private String siteNumber;
	private String street;
	private String city;
	private String zip;
	private String state;
	private String county;

	public Summerfood() {
	}

	public Summerfood(String siteName, String siteNumber) {
		this.siteName = siteName;
		this.siteNumber = siteNumber;
	}

	public Summerfood(String siteName, String siteNumber, String street,
			String city, String zip, String state, String county) {
		this.siteName = siteName;
		this.siteNumber = siteNumber;
		this.street = street;
		this.city = city;
		this.zip = zip;
		this.state = state;
		this.county = county;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SUMMERFOOD_ID", unique = true, nullable = false)
	public Integer getSummerfoodId() {
		return this.summerfoodId;
	}

	public void setSummerfoodId(Integer summerfoodId) {
		this.summerfoodId = summerfoodId;
	}

	@Column(name = "SITE_NAME", nullable = false, length = 250)
	public String getSiteName() {
		return this.siteName;
	}

	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	@Column(name = "SITE_NUMBER", unique = true, nullable = false, length = 45)
	public String getSiteNumber() {
		return this.siteNumber;
	}

	public void setSiteNumber(String siteNumber) {
		this.siteNumber = siteNumber;
	}

	@Column(name = "STREET", length = 250)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "CITY", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ZIP", length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "STATE", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTY", length = 45)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

}
