package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SummerfoodInfo generated by hbm2java
 */
@Entity
@Table(name = "SUMMERFOOD_INFO", catalog = "OREGONASKDB")
public class SummerfoodInfo implements java.io.Serializable {

	private static final long serialVersionUID = -4611757794087937577L;
	
	private Integer summerfoodInfoId;
	private String breakfast;
	private String lunch;
	private String supper;
	private String amSnack;
	private String pmSnack;
	private Integer year;

	public SummerfoodInfo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SUMMERFOOD_INFO_ID", unique = true, nullable = false)
	public Integer getSummerfoodInfoId() {
		return this.summerfoodInfoId;
	}

	public void setSummerfoodInfoId(Integer summerfoodInfoId) {
		this.summerfoodInfoId = summerfoodInfoId;
	}

	@Column(name = "BREAKFAST", length = 45)
	public String getBreakfast() {
		return this.breakfast;
	}

	public void setBreakfast(String breakfast) {
		this.breakfast = breakfast;
	}

	@Column(name = "LUNCH", length = 45)
	public String getLunch() {
		return this.lunch;
	}

	public void setLunch(String lunch) {
		this.lunch = lunch;
	}

	@Column(name = "SUPPER", length = 45)
	public String getSupper() {
		return this.supper;
	}

	public void setSupper(String supper) {
		this.supper = supper;
	}

	@Column(name = "AM_SNACK", length = 45)
	public String getAmSnack() {
		return this.amSnack;
	}

	public void setAmSnack(String amSnack) {
		this.amSnack = amSnack;
	}

	@Column(name = "PM_SNACK", length = 45)
	public String getPmSnack() {
		return this.pmSnack;
	}

	public void setPmSnack(String pmSnack) {
		this.pmSnack = pmSnack;
	}

	@Column(name = "YEAR", nullable = false)
	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

}
