package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SummerfoodInfoByYear generated by hbm2java
 */
@Entity
@Table(name = "SUMMERFOOD_INFO_BY_YEAR", catalog = "OREGONASKDB")
public class SummerfoodInfoByYear implements java.io.Serializable {

	private Integer summerfoodInfoByYearId;
	private int year;
	private int summerfoodId;
	private int summerfoodInfoId;

	public SummerfoodInfoByYear() {
	}

	public SummerfoodInfoByYear(int year, int summerfoodId, int summerfoodInfoId) {
		this.year = year;
		this.summerfoodId = summerfoodId;
		this.summerfoodInfoId = summerfoodInfoId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SUMMERFOOD_INFO_BY_YEAR_ID", unique = true, nullable = false)
	public Integer getSummerfoodInfoByYearId() {
		return this.summerfoodInfoByYearId;
	}

	public void setSummerfoodInfoByYearId(Integer summerfoodInfoByYearId) {
		this.summerfoodInfoByYearId = summerfoodInfoByYearId;
	}

	@Column(name = "YEAR", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "SUMMERFOOD_ID", nullable = false)
	public int getSummerfoodId() {
		return this.summerfoodId;
	}

	public void setSummerfoodId(int summerfoodId) {
		this.summerfoodId = summerfoodId;
	}

	@Column(name = "SUMMERFOOD_INFO_ID", nullable = false)
	public int getSummerfoodInfoId() {
		return this.summerfoodInfoId;
	}

	public void setSummerfoodInfoId(int summerfoodInfoId) {
		this.summerfoodInfoId = summerfoodInfoId;
	}

}
