package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SummerfoodLink generated by hbm2java
 */
@Entity
@Table(name = "SUMMERFOOD_LINK", catalog = "OREGONASKDB", uniqueConstraints = @UniqueConstraint(columnNames = "SUMMERFOOD_ID"))
public class SummerfoodLink implements java.io.Serializable {

	private Integer summerfoodLinkId;
	private Integer schoolId;
	private Integer sponsorId;
	private int summerfoodId;

	public SummerfoodLink() {
	}

	public SummerfoodLink(int summerfoodId) {
		this.summerfoodId = summerfoodId;
	}

	public SummerfoodLink(Integer schoolId, Integer sponsorId, int summerfoodId) {
		this.schoolId = schoolId;
		this.sponsorId = sponsorId;
		this.summerfoodId = summerfoodId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SUMMERFOOD_LINK_ID", unique = true, nullable = false)
	public Integer getSummerfoodLinkId() {
		return this.summerfoodLinkId;
	}

	public void setSummerfoodLinkId(Integer summerfoodLinkId) {
		this.summerfoodLinkId = summerfoodLinkId;
	}

	@Column(name = "SCHOOL_ID")
	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "SPONSOR_ID")
	public Integer getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(Integer sponsorId) {
		this.sponsorId = sponsorId;
	}

	@Column(name = "SUMMERFOOD_ID", unique = true, nullable = false)
	public int getSummerfoodId() {
		return this.summerfoodId;
	}

	public void setSummerfoodId(int summerfoodId) {
		this.summerfoodId = summerfoodId;
	}

}
