package org.oregonask.entities;
// Generated Oct 28, 2014 11:43:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * YmcacwLink generated by hbm2java
 */
@Entity
@Table(name = "YMCACW_LINK", catalog = "OREGONASKDB", uniqueConstraints = @UniqueConstraint(columnNames = "PROGRAM_ID"))
public class YmcacwLink implements java.io.Serializable {

	private Integer ymcacwLink;
	private Integer schoolId;
	private Integer sponsorId;
	private int programId;

	public YmcacwLink() {
	}

	public YmcacwLink(int programId) {
		this.programId = programId;
	}

	public YmcacwLink(Integer schoolId, Integer sponsorId, int programId) {
		this.schoolId = schoolId;
		this.sponsorId = sponsorId;
		this.programId = programId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "YMCACW_LINK", unique = true, nullable = false)
	public Integer getYmcacwLink() {
		return this.ymcacwLink;
	}

	public void setYmcacwLink(Integer ymcacwLink) {
		this.ymcacwLink = ymcacwLink;
	}

	@Column(name = "SCHOOL_ID")
	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "SPONSOR_ID")
	public Integer getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(Integer sponsorId) {
		this.sponsorId = sponsorId;
	}

	@Column(name = "PROGRAM_ID", unique = true, nullable = false)
	public int getProgramId() {
		return this.programId;
	}

	public void setProgramId(int programId) {
		this.programId = programId;
	}

}
