package org.oregonask.entities;
// Generated Jan 2, 2015 11:54:01 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.Hibernate;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Association generated by hbm2java
 */
@Entity
@Table(name = "ASSOCIATION")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="id")
public class Association implements java.io.Serializable,IEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String title;
	private String company;
	private String organization;
	private String committee;
	private String status;
	private Contact contact;

	public Association() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TITLE", length = 100)
	@JsonProperty("TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "COMPANY", length = 100)
	@JsonProperty("COMPANY")
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "ORGANIZATION", length = 100)
	@JsonProperty("ORGANIZATION")
	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	@Column(name = "COMMITTEE", length = 100)
	@JsonProperty("COMMITTEE")
	public String getCommittee() {
		return this.committee;
	}

	public void setCommittee(String committee) {
		this.committee = committee;
	}

	@Column(name = "STATUS", length = 100)
	@JsonProperty("STATUS")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@ManyToOne
	@JoinColumn(name = "CONTACT_FK", nullable=false, insertable=false, updatable=false)
	@JsonProperty("CONTACT")
	public Contact getContact() {
		return contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@Override
	public void initialize() {
		Hibernate.initialize(this.getContact());
	}

}
